---
- name: "Configure the EKS cluster with kubectl"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENV_NAME: "udacity-capstone"
  roles:
    - deployment
    - service
